apiVersion : apps/v1
kind: Deployment
metadata:
  name: juliakmazurevotingappredis 
spec:
  replicas: 1
  selector:
    matchLabels:
        name: sawtooth-0
  template:
    metadata:
      labels:
        app: juliakmazurevotingappredis 
    spec:
      containers:
        - name: juliakmazurevotingappredis 
          image: mycontainerjulia.azurecr.io/juliakmazurevotingappredis
          ports:
          - containerPort: 80