apiVersion : apps/v1
kind: Deployment
metadata:
  name: azure-vote-front 
spec:
  replicas: 1
  progressDeadlineSeconds: 120
  selector:
    matchLabels:
        app: azure-vote-front
  template:
    metadata:
      labels:
        app: azure-vote-front 
    spec:
      containers:
        - name: azure-vote-front 
          image: myk8cr.azurecr.io/azure-vote-front
          ports:
          - containerPort: 80