name: Build and deploy container to ACR
    
permissions:
  id-token: write
  contents: read

env:
  AZURE_WEBAPP_NAME: azure-vote
  ACR_NAME: myvotingacr84
  RESOURCE_GROUP: votingAppContainer84ac-rg
  
on:
  push:
    branches:
    - master
    - release/*
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Az CLI login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        az acr build --image ${{ env.AZURE_WEBAPP_NAME }}:${{ github.run_number }} --registry ${{ env.ACR_NAME }}.azurecr.io --file "azure-vote/Dockerfile" .

    - name: 'Deploy to Azure Container Instances'
      uses: 'azure/aci-deploy@v1'
      with:
        resource-group: $RESOURCE_GROUP
        dns-name-label: $RESOURCE_GROUP${{ github.run_number }}
        image: ${{ env.ACR_NAME }}.azurecr.io/${{ env.AZURE_WEBAPP_NAME }}:${{ github.run_number }}
        registry-login-server: ${{ env.ACR_NAME }}.azurecr.io
        registry-username: ${{ secrets.REGISTRY_USERNAME }}
        registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        name: ${{ env.AZURE_WEBAPP_NAME }}
        location: eastus2
