name: Build a container with ACR
    
permissions:
  id-token: write
  contents: read

env:
  AZURE_WEBAPP_NAME: azure-vote
  ACR_NAME: myvotingacr84
  
on:
  push:
    branches:
    - master
    - release/*
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Az CLI login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Build and push image to ACR TJ
      id: build-image
      run: |
        az acr build --image $AZURE_WEBAPP_NAME:${{ github.run_number }} --registry $ACR_NAME.azurecr.io --file "azure-vote/Dockerfile" .

